export const SET_USER = 'SET_USER';

export const SET_LEADS = 'SET_LEADS';
export const SET_LEADSLOADING = 'SET_LEADSLOADING';
export const UPDATE_LEAD = 'UPDATE_LEAD';
export const SET_UPDATELEAD = 'SET_UPDATELEAD';
export const DELETE_LEAD = 'DELETE_LEAD';
export const REFRESH_LEAD = 'REFRESH_LEAD';
export const SELECTED_LEAD = 'SELECTED_LEAD';
export const ADD_LEAD = 'ADD_LEAD';

export const SET_INVENTORY = 'SET_INVENTORY';
export const SET_INVENTORYLOADING = 'SET_INVENTORYLOADING';
export const UPDATE_INVENTORY = 'UPDATE_INVENTORY';
export const SET_UPDATEINVENTORY = 'SET_UPDATEINVENTORY';
export const DELETE_INVENTORY = 'DELETE_INVENTORY';

export const SET_CONTACT = 'SET_CONTACT';
export const ADD_CONTACT = 'ADD_CONTACT';
export const DELETE_CONTACT = 'DELETE_CONTACT';
export const DELETE_ORGANIZATION = 'DELETE_ORGANIZATION';
export const DELETE_PERSON = 'DELETE_PERSON';
export const SET_UPDATECONTACT = 'SET_UPDATECONTACT';
export const SET_ORGANIZATION = 'SET_ORGANIZATION';
export const SET_UPDATEORG = 'SET_UPDATEORG';
export const SET_PERSONS = 'SET_PERSONS';

export const SET_ALERT = 'SET_ALERT';

export const SET_CONFIRMATION = 'SET_CONFIRMATION';

export const SHOW_FOLLOWUP = 'SHOW_FOLLOWUP';
export const SHOW_LEADCREATE = 'SHOW_LEADCREATE';
export const SHOW_CONTACTCREATE = 'SHOW_CONTACTCREATE';
export const SHOW_ORGCREATE = 'SHOW_ORGCREATE';
